### ISSUE TITLE
[POST] The hermeticism and rigidity of Xcode and its projects

### ISSUE THREAD

**Issue by pepibumur** [pepibumur/website#10]
https://ppinera.es/2018/01/28/xcode-rigidity-hermeticism.html

**Comment by pepibumur** [comment]
Test

**Comment by esttorhe** [comment]
I'm super curious about the comments/issues implementation.

Considering adopting this for my blog 😄

**Comment by pepibumur** [comment]
Nice! I'm using React, fetching the JSON using [gh-commentify](https://github.com/orta/gh-commentify) and rendering a component list in a comment `div` section. I'm still building the layout *(CSS is not my thing)*, but I'll ping you once it's done!

**Comment by pepibumur** [comment]
```swift
let name = "Pedro"
```

**Comment by pepibumur** [comment]
@esttorhe I felt tempted to copy the GitHub style :).

![image](https://user-images.githubusercontent.com/663605/35542920-755f60c4-0530-11e8-856a-1c8c02a4daba.png)
