### ISSUE TITLE
[POST] Stress

### ISSUE THREAD

**Issue by pepibumur** [pepibumur/website#19]

**Comment by dyrkabes** [comment]
Good luck dealing with your problem. I think any of us experience something similar (I do) and sometimes it could lead to circumstances where the brain or the environment will make us stop. You are in the right direction I think. The constant rush is what makes us blind. And the more a person rushes the more it wants to rush, working for 10, 12, 14 hours per day. But that's never enough
Btw, good post, thank you

**Comment by pepibumur** [comment]
Thank you very much @dyrkabes. I'm learning to go slower and not push myself too hard. Before that, it was very uncomfortable not reading about technology or doing something not related to work. Nowadays, I try to find other distractions and things to do, which is fresh air for my brain.
