### ISSUE TITLE
[POST] All you need is tools

### ISSUE THREAD

**Issue by pepibumur** [pepibumur/website#27]

**Comment by Austinate** [comment]
Thanks for sharing!
Can you share any info on ways your team measures usage of tools? 
Do yo make data anonymous? Is data gathering opt-in? Do you think answers to both previous questions should be different for public/private projects?

**Comment by pepibumur** [comment]
You are welcome. Answering your questions:

> Can you share any info on ways your team measures usage of tools?

We use [StatsD](https://www.datadoghq.com/) for normal metrics, and [Bugsnag](https://www.bugsnag.com/) for errors. We have a few dashboards created to see the usage and prioritize our work based on it.

> Do you make data anonymous? Is data gathering opt-in?

No, because those tools are internal. Data gathering is not opt-in because collecting that data is important for us to improve the tools that our teams are using. It'd be a different story if the tools were for public usage, like Fastlane.

> Do you think answers to both previous questions should be different for public/private projects?

The tools that I talk about in the blog post are internal. If they were public, we'd design them paying especial attention to privacy.

**Comment by s4cha** [comment]
Really cool article 👍

**Comment by pepibumur** [comment]
Thank you very much @s4cha. I'm glad that you liked it 😃
